### PR TITLE
Feat: Added Question Filter, View, Edit, and delete for Categories, and Difficulties. 

### PR DESCRIPTION
**Pull request by JMark-FS**
Things to QA
- Test if the Question filtering works.
- Test if View, edit, and delete category works.
- Test if View, edit, and delete difficulty works.
- Test if view question works.
- Test if Edit Question statement works. (Update is made onBlur)
- Test if Edit Question Category, and Question Difficulty Works. 
- Test if Updating the answer works.

note: Puzzle question may have a bug on edit.

### CODE REVIEW

**Review by jaymar921 — APPROVED** [review]
all goods

**Comment by jumapaoA** [comment]
> * Test if View, edit, and delete category works.

Edit Category button redirect to a 404 page, but edit button under kebab menu is okay

**Comment by jumapaoA** [comment]
https://trello.com/c/jJCVPtlp/17-alyssa-qa-for-pr-105 check tickets under this link to view list of issues found.

**Comment by jaymar921** [comment]
long debate 💌

**Review by jumapaoA — APPROVED** [review]
all goods

**Pull request merged**
