### PR TITLE
Feature/roomaudittrail

### PR DESCRIPTION
**Pull request by nealsotes**
This pull request enhances the RoomService in the QuizMaster application by adding comprehensive audit trail functionality for room-related operations, including create, update, and delete events.

Changes:
Modified the CreateRoom, UpdateRoom, and DeleteRoom methods in RoomService to capture user details and include audit trails.
Introduced a new gRPC service (RoomAuditService) for logging room-related audit events.
Created CreateRoomEvent, UpdateRoomEvent, and DeleteRoomEvent to represent the event structures for room operations in the audit trail.
Updated the proto file (roommonitoringaudit.proto) to include the new gRPC service and the event messages.
Ensured that old values are included in the audit events for update and delete operations.

### CODE REVIEW

**Review by jaymar921 — APPROVED** [review]
all goods

**Review by JMark-FS — COMMENTED** [review]
lgtm

**Review by JMark-FS — APPROVED** [review]
lgtm

**Comment by jaymar921** [comment]
merged

**Pull request merged**
