### PR TITLE
Feat: JWT Authorization Bearer Implementation

### PR DESCRIPTION
**Pull request by jaymar921**
# JWT Authorization Bearer Implementation
- `Feature:` Aside from Cookie Authentication (🍪), The system will now accept requests with Authorization header that has JWT Token in it, it will be decoded in the backend and could let the request pass or return unauthorized.
- `Refactor:` AuthRequest was replaced to AuthenticationRequestDTO as the login model request body.

### For Testers
I would encourage you to use the API-GATEWAY endpoints.
- Access via Swagger: https://localhost:7081/swagger/index.html
- Access via Postman:
 Import this link to the postman collection: https://localhost:7081/swagger/v1/swagger.json

> Happy coding 😃 
Figure

### CODE REVIEW

**Review by HaroldCuico — APPROVED** [review]
all goods

**Comment by jaymar921** [comment]
@JMark-FS pa review lods
image

**Review by JMark-FS — APPROVED** [review]
Looks good

**Review by JMark-FS — APPROVED** [review]
Looks good

**Pull request merged**
