### PR TITLE
Feature/System Modules

### PR DESCRIPTION
**Pull request by jaymar921**
# System Modules
This Pull Request includes the following features and bugfix:
- Edit and Retrieval of System Information
- Edit and Retrieval of Contact Information 
- Users to submit contact request (reach out the devs)
- Users to submit system review (can be unauthorized for anonymous review)
- Retrieve System Reviews (admin only)
- Retrieve submitted contact request (admin only)
- Fixed the token expire issue error, just added an exception handling to the JWTHelper class

Note: I have a temporary email credentials exposed in the [appsettings.json](https://github.com/FS-FAST-TRACK/QuizMaster/blob/develop/WebApp/backend/QuizMaster.API.Gatewway/appsettings.json), I will be removing it once the testing is done

### CODE REVIEW

**Review by hinacay — APPROVED** [review]
everything looks good to me. no comments for now

**Review by jumapaoA — APPROVED** [review]
All goods.

**Comment by jaymar921** [comment]
thank you team

**Review by HaroldCuico — APPROVED** [review]
LGTM

**Pull request merged**
