### PR TITLE
Feature/system-reports

### PR DESCRIPTION
**Pull request by jaymar921**
# Quiz Report
The reportDTO will contain the ff:
- Answers of each participants which also has screenshot links in Array form
- Leaderboard, scores of participants
- number of participants in that current session
- hostName
- hostId
- roomId (only stored the ID, the room data can be fetched via API)
- startTime
- endTime

For testing you’ll need the ff:
- run the backend: QuizMaster backend
- run the quiz-session frontend: Quizmaster-Session

Step 1: npm run dev the frontend Quiz-session and type: localhost:3000
Step 2: Login, proceed to localhost:3000/auth and enter the username and password
Step 3: Once authenticated, enter a room pin, make sure that a room was created via backend(swagger) for now.
Step 4: Create another instance, since this is a multiplayer game, we need 2 users logged-in the same room, one must be admin and one must be user
Step 5: Start the Quiz and let it finish
Step 6: in the backend, do the gateway/api/system/quiz_report route and do the QA

image 
image
image

### CODE REVIEW

**Comment by jaymar921** [comment]
[current](https://github.com/FS-FAST-TRACK/QuizMaster/commit/e40b4576f2135cc37dda354fc27069f7dd707dab) merged to develop, hoping no merge conflicts

**Review by HaroldCuico — APPROVED** [review]
LGTM

**Review by jumapaoA — APPROVED** [review]
LGTM

**Comment by jaymar921** [comment]
merged

**Pull request merged**
