### PR TITLE
feat: Added test for Question Controller. 

### PR DESCRIPTION
**Pull request by JMark-FS**
Description

- Added test to check that a controller using a repository with empty questions, returns empty result.

### CODE REVIEW

**Review by jaymar921 — APPROVED** [review]
Approved!
Figure

**Review by HaroldCuico — APPROVED** [review]
all goods

**Comment by jaymar921** [comment]
yow

**Comment by jaymar921** [comment]
main man lahos HAHAHA

**Comment by jaymar921** [comment]
all goods
Figure

You can now merge to `develop`

**Pull request merged**
